/**
 * avatar-poses.ts (A-bis) — pose/expression variant export pipeline for the interactive hero avatar.
 *
 * Imports:  node:fs, node:path, node:url, sharp.
 * Inputs:   the background-removed variant cutouts at
 *             content/media/avatar/redesign-v2/poses/<name>-cutout.png   (880×1168, RGBA)
 *           and the deployed base avatar public/avatar/avatar.webp        (1440×1800, RGBA) as the
 *           alignment REFERENCE (it is exactly what renders on screen, so variants align to it).
 * Outputs:  public/avatar/<name>.webp                                     (1440×1800, RGBA, ≤~150 kB)
 * Data/instruction: no network, no secrets — pure local image transform run via `pnpm media:poses`.
 *
 * WHY normalization: the variants were generated by gpt_image_2_5 (`image_references`) which only
 * offers 3:4, not the hero's 4:5 frame, and doesn't hold exact framing — each variant is ~10–15%
 * tighter/shifted than the base. A raw swap would visibly jump. This script re-frames every variant
 * to the base's subject SIZE and POSITION so `AvatarScene` can crossfade between them cleanly:
 *   1. find the subject's alpha bounding box AND the HEAD width in the base and in each variant.
 *      (The shoulder/arm span is NOT a valid anchor here: the arms-crossed elbows reach the frame
 *      edges in both base and variants, so the bbox width is just the frame width and hides the
 *      variants' ~15% zoom-in. The head is the load-bearing feature for a face swap, so we anchor
 *      on it — the widest opaque run within the top HEAD_ZONE_FRAC of the subject, i.e. the hair.)
 *   2. scale the variant so its HEAD width matches the base head width (shrinks the zoomed-in
 *      variants so every face reads at the same size);
 *   3. place the scaled subject so the head's horizontal centre and the subject TOP edge (top of
 *      hair) land where the base's do — so the face sits in the same place in the 4:5 frame;
 *   4. composite onto a 1440×1800 transparent canvas (clipping any overflow), erode the alpha
 *      matte by ERODE_PX to kill the render's dark rim (same fix as scripts/avatar.ts), and encode
 *      webp down a quality ladder until ≤ MAX_BYTES.
 * A crossfade in AvatarScene masks any residual sub-pixel drift; this step removes the gross jump.
 *
 * NOTE on erosion: sharp's joinChannel/ensureAlpha survives poorly across a WebP re-encode in this
 * sharp version (it reports hasAlpha but silently drops the channel on write). As in scripts/avatar.ts
 * we erode by rewriting the alpha byte of a raw interleaved RGBA buffer, then ingest that raw buffer.
 */
import { existsSync, statSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

type SharpInstance = ReturnType<typeof sharp>;

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const POSES_DIR = resolve(ROOT, "content/media/avatar/redesign-v2/poses");
const BASE = resolve(ROOT, "public/avatar/avatar.webp");
const OUT_DIR = resolve(ROOT, "public/avatar");

const CANVAS_W = 1440;
const CANVAS_H = 1800;
// Matte refinement order: FEATHER first (light anti-alias), then ERODE (pull the alpha contour in
// past the render's edge fringe). The variant cutouts are now 1792px 2k renders (medium quality,
// background:transparent → remove_background), DOWNSCALED to the 1440 canvas — a crisp matte, so this
// matches the base's light touch (base uses erode 3, no feather) rather than the heavy pass the old
// 880px upscaled gens needed. A hair of feather keeps the downscaled edge clean.
const FEATHER_SIGMA = 0.6; // Gaussian blur on the ALPHA channel only, to anti-alias the matte.
const ERODE_PX = 3; // erosion after feather — clears the render's thin edge fringe (as scripts/avatar.ts).
const ALPHA_THRESHOLD = 16; // alpha byte above which a pixel counts as "subject" for the bbox.
const HEAD_ZONE_FRAC = 0.32; // top fraction of the subject height treated as the head zone (hair→jaw).
const MAX_BYTES = 158_000; // ~154 kB ceiling (HANDOFF A-bis: keep each ≤~150 kB like avatar.webp).
const QUALITY_LADDER = [80, 76, 72, 68];

// Variant basenames; each has a matching <name>-cutout.png input and produces <name>.webp.
const VARIANTS = [
  "avatar-gaze-laptop",
  "avatar-gaze-book",
  "avatar-gaze-plant",
  "avatar-smile",
  "avatar-thinking",
  "avatar-surprised",
  "avatar-ask-lean",
] as const;

interface Metrics {
  /** subject bbox */
  x: number;
  y: number;
  w: number;
  h: number;
  /** head anchor: widest opaque run within the top HEAD_ZONE_FRAC of the subject */
  headW: number;
  headCenterX: number;
  imgW: number;
  imgH: number;
}

/**
 * Subject alpha bbox + head anchor. The head anchor is the widest single row of opaque pixels within
 * the top HEAD_ZONE_FRAC of the subject height (the hair crown / temples), which tracks head size and
 * horizontal position far more reliably than the arms-crossed shoulder span (which is edge-clipped).
 */
async function measure(buffer: Buffer): Promise<Metrics> {
  const { data, info } = await sharp(buffer)
    .ensureAlpha()
    .extractChannel("alpha")
    .raw()
    .toBuffer({ resolveWithObject: true });
  const { width, height } = info;
  let minX = width;
  let minY = height;
  let maxX = -1;
  let maxY = -1;
  for (let y = 0; y < height; y += 1) {
    const row = y * width;
    for (let x = 0; x < width; x += 1) {
      if (data[row + x]! > ALPHA_THRESHOLD) {
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
    }
  }
  if (maxX < 0) throw new Error("measure: image has no opaque pixels");
  const bx = minX;
  const by = minY;
  const bw = maxX - minX + 1;
  const bh = maxY - minY + 1;

  // Widest opaque row in the head zone → head width + centre.
  const zoneBottom = by + Math.round(bh * HEAD_ZONE_FRAC);
  let headW = 0;
  let headCenterX = bx + bw / 2;
  for (let y = by; y < zoneBottom; y += 1) {
    const row = y * width;
    let rowMin = width;
    let rowMax = -1;
    for (let x = 0; x < width; x += 1) {
      if (data[row + x]! > ALPHA_THRESHOLD) {
        if (x < rowMin) rowMin = x;
        if (x > rowMax) rowMax = x;
      }
    }
    const rowW = rowMax - rowMin + 1;
    if (rowMax >= 0 && rowW > headW) {
      headW = rowW;
      headCenterX = (rowMin + rowMax) / 2;
    }
  }
  if (headW <= 0) throw new Error("measure: no opaque row found in the head zone (degenerate cutout)");
  return { x: bx, y: by, w: bw, h: bh, headW, headCenterX, imgW: width, imgH: height };
}

/**
 * Refines the alpha matte of a raw-RGBA-backed sharp instance: FEATHER first (Gaussian blur on the
 * alpha channel only, to anti-alias the coarse upscaled matte's stair-steps) THEN ERODE by `px`
 * (morphological erosion, to pull the alpha contour inward past the dark backdrop-contaminated edge
 * band). Order matters — see the FEATHER_SIGMA/ERODE_PX note. RGB bands are left untouched.
 */
async function refineAlpha(image: SharpInstance, px: number, featherSigma: number): Promise<SharpInstance> {
  if (px <= 0 && featherSigma <= 0) return image;
  const png = await image.png().toBuffer();
  const src = sharp(png);
  const { data: rgba, info } = await src.clone().ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  let alphaPipe = src.clone().ensureAlpha().extractChannel("alpha");
  if (featherSigma > 0) alphaPipe = alphaPipe.blur(featherSigma);
  if (px > 0) alphaPipe = alphaPipe.erode(px);
  const { data: erodedAlpha } = await alphaPipe.raw().toBuffer({ resolveWithObject: true });
  const combined = Buffer.from(rgba);
  const pixelCount = info.width * info.height;
  for (let i = 0; i < pixelCount; i += 1) {
    combined[i * 4 + 3] = erodedAlpha[i]!;
  }
  return sharp(combined, { raw: { width: info.width, height: info.height, channels: 4 } });
}

async function encodeUnderBudget(image: SharpInstance, outPath: string): Promise<{ bytes: number; quality: number }> {
  const prepared = await image.png().toBuffer(); // freeze the composited pixels once.
  let bytes = Infinity;
  let quality = QUALITY_LADDER[QUALITY_LADDER.length - 1]!;
  for (const q of QUALITY_LADDER) {
    await sharp(prepared).webp({ quality: q, alphaQuality: 90, effort: 6 }).toFile(outPath);
    bytes = statSync(outPath).size;
    quality = q;
    if (bytes <= MAX_BYTES) break;
    console.log(`  ${outPath.split("/").pop()} @q${q} = ${bytes} B (> ${MAX_BYTES}), stepping down`);
  }
  return { bytes, quality };
}

async function processVariant(name: string, base: Metrics): Promise<void> {
  const inPath = resolve(POSES_DIR, `${name}-cutout.png`);
  if (!existsSync(inPath)) throw new Error(`missing input cutout: ${inPath}`);

  const cutout = await sharp(inPath).ensureAlpha().png().toBuffer();
  const v = await measure(cutout);

  // Scale the whole variant so its HEAD width equals the base head width (equalises face size).
  const scale = base.headW / v.headW;
  const scaledW = Math.round(v.imgW * scale);
  const scaledH = Math.round(v.imgH * scale);
  const scaledBuf = await sharp(cutout)
    .resize({ width: scaledW, height: scaledH, fit: "fill" })
    .ensureAlpha()
    .png()
    .toBuffer();

  // Align (in scaled coords): head centre-x → base head centre-x; subject top → base subject top.
  const scaledHeadCenterX = v.headCenterX * scale;
  const scaledTop = v.y * scale;
  const offsetX = Math.round(base.headCenterX - scaledHeadCenterX);
  const offsetY = Math.round(base.y - scaledTop);

  // Clip the scaled variant to the region that lands inside the 1440×1800 canvas.
  const srcLeft = Math.max(0, -offsetX);
  const srcTop = Math.max(0, -offsetY);
  const dstLeft = Math.max(0, offsetX);
  const dstTop = Math.max(0, offsetY);
  const visW = Math.min(scaledW - srcLeft, CANVAS_W - dstLeft);
  const visH = Math.min(scaledH - srcTop, CANVAS_H - dstTop);
  if (visW <= 0 || visH <= 0) throw new Error(`${name}: variant does not overlap the canvas`);

  const region = await sharp(scaledBuf)
    .extract({ left: srcLeft, top: srcTop, width: visW, height: visH })
    .png()
    .toBuffer();

  const canvas = sharp({
    create: { width: CANVAS_W, height: CANVAS_H, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } },
  }).composite([{ input: region, left: dstLeft, top: dstTop }]);

  const refined = await refineAlpha(canvas, ERODE_PX, FEATHER_SIGMA);
  const outPath = resolve(OUT_DIR, `${name}.webp`);
  const { bytes, quality } = await encodeUnderBudget(refined, outPath);
  const meta = await sharp(outPath).metadata();
  console.log(
    `${name}.webp — ${bytes} B, q${quality}, ${meta.width}×${meta.height}, hasAlpha=${meta.hasAlpha} ` +
      `(scale ${scale.toFixed(3)}, offset ${offsetX},${offsetY})`,
  );
}

async function main(): Promise<void> {
  if (!existsSync(BASE)) {
    console.error(`avatar-poses.ts: base reference not found at ${BASE} (run \`pnpm media:avatar\` first)`);
    process.exit(1);
  }
  const baseBuf = await sharp(BASE).ensureAlpha().png().toBuffer();
  const base = await measure(baseBuf);
  // Sanity-guard the reference: a real background-removed bust has a head far narrower than the frame.
  // A ratio near 1 means the base has no true alpha (e.g. a fully-opaque render) and every variant
  // would be scaled to a bogus "head" — fail loudly instead of writing mis-sized outputs.
  const headRatio = base.headW / base.w;
  if (headRatio < 0.1 || headRatio > 0.95) {
    console.error(
      `avatar-poses.ts: base head/width ratio ${headRatio.toFixed(2)} is implausible — is ${BASE} ` +
        `a real background-removed cutout with alpha? Aborting rather than mis-scaling the variants.`,
    );
    process.exit(1);
  }
  console.log(
    `base: bbox x=${base.x} y=${base.y} w=${base.w} h=${base.h} · headW=${base.headW} ` +
      `headCx=${base.headCenterX.toFixed(0)} (in ${base.imgW}×${base.imgH})`,
  );
  for (const name of VARIANTS) {
    await processVariant(name, base);
  }
}

main().catch((err) => {
  console.error("avatar-poses.ts: failed", err);
  process.exit(1);
});
